### ISSUE TITLE
Override !help to actually be helpful

### ISSUE THREAD

**Issue by synsypa** [play4honor/discord_quote_bot#44]
current help message is autogenerated and not especially meaningful. I assume the API allows you to override it with your own message.

**Comment by zhangchuck** [comment]
https://github.com/zhangchuck/discord_quote_bot/commit/f3e17f55e1fa7c96495ab1ae4dea712599d183a9

Looks like we can get decent documentation in `!help` by:

- adding a docstring to the calling function
- using the right term for argument (e.g., message_id)

![image](https://user-images.githubusercontent.com/4514597/64939528-24cff780-d816-11e9-99f1-1a3104eae444.png)
