### ISSUE TITLE
Placeholder for attached image.

### ISSUE THREAD

**Issue by DoubleSec** [play4honor/discord_quote_bot#47]
When quoting a message with an attached image and no other text, the bot returns only empty string in a block quote:
![image](https://user-images.githubusercontent.com/20446965/69682223-57983680-1076-11ea-979b-8649721c6b0b.png)
It might make sense to at least add some kind of placeholder text for an attached image, or possibly explore reattaching?

**Comment by zhangchuck** [comment]
- We need an example of this kind of message. (i.e., the message URL) so we can test
- Reattaching should be pretty simple if we can do it via the `file=` or `embed=` argument
    - Not sure which one it should be, we need to inspect the example message object to figure out how the image is stored
- Is this a problem for messages with both text and an image?

**Comment by DoubleSec** [comment]
For example: `https://discordapp.com/channels/106536439809859584/202198069691940865/750823582497767626`

Quoting this with `!quote https://discordapp.com/channels/106536439809859584/202198069691940865/750823582497767626 For example.`

gets you:
![image](https://user-images.githubusercontent.com/20446965/92188606-aa332a00-ee22-11ea-9e35-a3a7d29b431b.png)

For a message with both image and text:
`!quote https://discordapp.com/channels/106536439809859584/202198069691940865/750533659085504514`
gets:
![image](https://user-images.githubusercontent.com/20446965/92188701-ec5c6b80-ee22-11ea-95a0-4556e5dd9eb5.png)
There's no indication there was an image originally attached.
