### ISSUE TITLE
Cross-Channel Quoting

### ISSUE THREAD

**Issue by zhangchuck** [play4honor/discord_quote_bot#61]
- Leftover from #56, we want to enable cross-channel quoting

# Expected Behavior

1. Hit "Copy Message Link" in channel A (which discord_quote_bot exists in)
2. Go to channel B (which discord_quote_bot is also a member of) and write `!q [message link]`
3. Retrieve the message from channel A and quote it in channel B

## Additional Behavior?

- make sure the jumplink works properly?
- make sure in `format_quote` what channel it came from?
- inform channel A that a message has been quoted in channel B?
 
# Suggested Implementation
- define `channel_id = None` here: https://github.com/play4honor/discord_quote_bot/blob/2eec1f2936f596e8e7f361050a83fd11959020c4/discord_quote/discord_quote/discord_quote.py#L133
- define `channel_id` here: https://github.com/play4honor/discord_quote_bot/blob/2eec1f2936f596e8e7f361050a83fd11959020c4/discord_quote/discord_quote/discord_quote.py#L141
- check for `channel_id` existence here: https://github.com/play4honor/discord_quote_bot/blob/2eec1f2936f596e8e7f361050a83fd11959020c4/discord_quote/discord_quote/discord_quote.py#L156
- if `channel_id` is not None, then have to retrieve the message in a different way
- otherwise, assume the `channel_id` is the current ctx channel and use the current command
- might need to adjust the message formating?

**Comment by zhangchuck** [comment]
Probably relevant:

https://discordpy.readthedocs.io/en/latest/faq.html?highlight=ctx%20channel#how-do-i-send-a-message-to-a-specific-channel

**Comment by zhangchuck** [comment]
Actually, let's explicitly set `channel_id` for numeric methods, to reduce conditionals.

**Comment by synsypa** [comment]
There's going to be significant permission leakage with cross-channel quoting, particularly if you want to include jumplinks to the channels. Couple options I can think of to manage this:

1. Function should check if all viewers in the current channel can read the target channel (Most complicated)
2. Function should return "said Elsewhere" instead of jumplinking the quote location 

(Aside, IMO cross-quote notification clutter and should not be default on, and frankly is not something that I believe should ever be sent to channel, at best it should be send as DM to the quotee)

**Comment by zhangchuck** [comment]
Two separate issues:

1. **Message security.** I think we discussed this initially. If Alice can quote in channel 1 what Bob said in channel 2, then Alice (a) has access to the message jump-url and (b) quote bot has access to both channel 1 and channel 2. Alice could conceivably just copy and paste or screen shot the message.
    - Could Carol who live in channel 1 quote something she does not have access to? (not sure, maybe if she guessed the channel 2 `channel_id` and a `message_id`)?
    - Could Derek, who isn't part of the server (but part of another server with another instance of discord_quote_bot) quote something he does not have access to? Not an issue atm since it's only on one server, but how does this interact with server permissions for the bot. I
2. **Nusiance.** I think cross-channel quoting notification is a nice way to get people to jump between conversation in two channels. I'm okay with the DM version of this as well, although that's separate from the message security issue.
    - If we do the DM version of this, do we want to include links? Or will this be like the LinkedIn feature where "someone from cisco viewed your profile".

**Comment by synsypa** [comment]
so re: message permissions, the use case that I'm concerned about is if Alice quotes into Channel 1 what Bob said in Channel 2, but Carol doesn't have permissions to Channel 2/doesn't know Channel 2 exists (i.e. maybe a mod only channel)
