### ISSUE TITLE
Yoshi's pin feature

### ISSUE THREAD

**Issue by zhangchuck** [play4honor/discord_quote_bot#71]
Since no one else wanted to write the issue...

# Proposed Interface

## Store a new pin

```
!put [messsage_link] [alias]
!p [message_link] [alias]
```
1. Use the command in a chatroom
1. Bot deletes the request
2. Bot stores [message_link], [alias], request time and pinner into a database (see schema)

Notes:

- Alias to be required? **Yes**
- Or we could have some default format `AZ_1`
- aliases should be case_insensitive and no spaces **And also <25 characters**

## Get an old pin

```
!get [alias] 
!g [alias]
```

1. Delete the request
2. Retrieve the old message link and quote it
3. If alias not found, suggest some alternatives?

## Search old pins

```
!pin list [n] [query] 
!l [query]
```

1. Delete the request in chatroom
2. Bot DMs the requester with the top [n] (or 10) queries that are similar to the alias or username

Notes:
- if we want more robust search functionality, then we need to also store the message...

# Proposed Implementation

## AWS

1. Create a bucket
2. Grab read/write credentials

## SQLite

1. Store pins in a local SQLite file within the docker's local filesystem
2. Allow docker image to accept a s3 bucket and credential
3. Turn versioning on in the s3 bucket
3. If no SQLite file exists, retrieve the database from S3 (if exists) or create a new file
4. ~~If SQLite file exists, check every X minutes if the local SQLite file and the SQLite file in the bucket have changed.~~
5. ~~If there is a change, upload and replace the SQLite file to the bucket~~
4. Whenever there is a pin, upload the SQLite file as a backup.

- Force us to wait for the upload to complete before accepting any more pins?
- There may be some weird race conditions/corner cases, but versioning should allow us to recover from these errors. Perhaps there's a way to keep track of which one has the newer data?

## Schema

```
alias
message_link
pinner
pin_time
```

**Comment by DoubleSec** [comment]
Surely it's better to trigger the S3 load when a message is pinned, rather than polling for state changes periodically.

**Comment by zhangchuck** [comment]
I wanted to batch it, but you're probably right that pins are infrequent enough that a PUT per pin is better.

**Comment by synsypa** [comment]
late note, but I think it depends on your main concern. Batching helps us directly control I/O rate from s3, which is nice since we're on limited (free tier) rate, but triggering on pin is probably more "correct"

**Comment by zhangchuck** [comment]
Issue with deployment was that we ran out of diskspace and the image wouldn't download properly. To fix this, we make sure to prune docker every time we redeploy:

https://github.com/play4honor/p4h_webhooks/commit/b8d26758326d3b21a699516a668e69d121dcedea
